[Server]
host = 0.0.0.0
port = 3080
ssl = False
auth = False
report_errors = False

images_path = /var/lib/gns3/library/images
projects_path = /var/lib/gns3/projects
appliances_path = /var/lib/gns3/library/appliances
symbols_path = /var/lib/gns3/library/symbols
configs_path = /var/lib/gns3/library/configs
resources_path = /var/lib/gns3/library/resources

ubridge_path = /usr/bin/ubridge
default_nat_interface = virbr0

console_start_port_range = 5000
console_end_port_range = 10000

vnc_console_start_port_range = 5900
vnc_console_end_port_range = 10000

udp_start_port_range = 20000
udp_end_port_range = 30000

enable_builtin_templates = True
install_builtin_appliances = True

[VPCS]
vpcs_path = /usr/bin/vpcs

[Qemu]
enable_kvm = True
require_kvm = True
enable_hardware_acceleration = True
require_hardware_acceleration = False
allow_unsafe_options = False
